<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-13 03:58:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class ProtoBackendAccessResource extends AutoProtoBackendAccessResource {/*_*/}
?>