<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBackendUserDAO extends BaseEntityDAO
	{
		public function getTable()
		{
			return 'backend_user';
		}
		
		public function getObjectName()
		{
			return 'BackendUser';
		}
		
		public function getSequence()
		{
			return 'backend_user_id_seq';
		}
	}
?>