<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-13 03:58:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class BackendAccessResource extends AutoBackendAccessResource implements Prototyped, DAOConnected
	{
		/**
		 * @return BackendAccessResource
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return BackendAccessResourceDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('BackendAccessResourceDAO');
		}
		
		/**
		 * @return ProtoBackendAccessResource
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoBackendAccessResource');
		}
		
		// your brilliant stuff goes here
	}
?>