<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-11 12:53:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

class BackendUser extends AutoBackendUser implements Prototyped, DAOConnected
{
	/**
	 * @return BackendUser
	**/
	public static function create()
	{
		return new self;
	}

	/**
	 * @return BackendUserDAO
	**/
	public static function dao()
	{
		return Singleton::getInstance('BackendUserDAO');
	}

	/**
	 * @return ProtoBackendUser
	**/
	public static function proto()
	{
		return Singleton::getInstance('ProtoBackendUser');
	}

	// your brilliant stuff goes here
	public function getDisplayName()
	{
		if(!$this->getLastName() && !$this->getFirstName()) {
			return $this->getLogin();
		}

		$displayName = $this->getFirstName();

		$displayName .= ' ' . $this->getLastName();

		return $displayName;
	}
}