<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-05-28 01:23:15                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class BaseEntityWithTexts extends AutoBaseEntityWithTexts implements Prototyped
	{
		/**
		 * @return BaseEntityWithTexts
		**/
		public static function create()
		{
			return new self;
		}
		
		
		/**
		 * @return ProtoBaseEntityWithTexts
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoBaseEntityWithTexts');
		}
		
		// your brilliant stuff goes here
	}
?>