<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-13 03:58:19                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

class EnumBackendAccessResourceType extends Enum
{
	const CONTROLLER = 'controller';
	const CONTROLLER_ACTION = 'controller_action';

	protected static $names = array(
		1 => self::CONTROLLER,
		2 => self::CONTROLLER_ACTION
	);


	public static function getAnyId()
	{
		return 1;
	}


	public static function controller()
	{
		return new self(1);
	}


	public static function controllerAction()
	{
		return new self(2);
	}
}