<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-04-11 12:53:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class BackendUserRoleParentDAO extends OneToManyLinked
	{
		public function __construct(BackendUserRole $backendUserRole, $lazy = false)
		{
			parent::__construct(
				$backendUserRole,
				BackendUserRole::dao(),
				$lazy
			);
		}


		/**
		 * @return BackendUserRoleParentDAO
		**/
		public static function create(BackendUserRole $backendUserRole, $lazy = false)
		{
			return new self($backendUserRole, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'parent_id';
		}
	}
?>