<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-05-06 10:22:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class BackendUserRolePermissionsDAO extends ManyToManyLinked
	{
		public function __construct(BackendUserRole $backendUserRole, $lazy = false)
		{
			parent::__construct(
				$backendUserRole,
				BackendAccessResource::dao(),
				$lazy
			);
		}
		
		/**
		 * @return BackendUserRolePermissionsDAO
		**/
		public static function create(BackendUserRole $backendUserRole, $lazy = false)
		{
			return new self($backendUserRole, $lazy);
		}
		
		public function getHelperTable()
		{
			return 'backend_user_role__backend_access_resource';
		}
		
		public function getChildIdField()
		{
			return 'backend_access_resource_id';
		}
		
		public function getParentIdField()
		{
			return 'backend_user_role_id';
		}
	}
?>