<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-05-28 01:23:15                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	abstract class BaseNonEntityWithTextsDAO extends AutoBaseNonEntityWithTextsDAO
	{
		// your brilliant stuff goes here
	}
?>