<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-05-16 20:33:06                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

abstract class BaseEntityDAO extends AutoBaseEntityDAO
{
	// your brilliant stuff goes here
}