<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	class EmployeeDAO extends AutoEmployeeDAO
	{
		// your brilliant stuff goes here
	}
?>