<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBackendUserRole extends ProtoBaseEntity
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'parent' => LightMetaProperty::fill(new LightMetaProperty(), 'parent', 'parent_id', 'identifier', 'BackendUserRole', null, false, false, false, 1, 2),
						'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 255, true, true, false, null, null),
						'title' => LightMetaProperty::fill(new LightMetaProperty(), 'title', null, 'string', null, 255, true, true, false, null, null),
						'permissions' => LightMetaProperty::fill(new LightMetaProperty(), 'permissions', 'backend_access_resource_id', 'identifierList', 'BackendAccessResource', null, false, false, false, 3, null),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'BackendUserRole', 4, true, true, false, null, null)
					)
				);
		}
	}
?>