<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBaseEntityWithTexts extends ProtoBaseEntity
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'textShort' => LightMetaProperty::fill(new LightMetaProperty(), 'textShort', 'text_short', 'string', null, 2048, false, true, false, null, null),
						'text' => LightMetaProperty::fill(new LightMetaProperty(), 'text', null, 'string', null, 2048, false, true, false, null, null),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'BaseEntityWithTexts', 4, true, true, false, null, null)
					)
				);
		}
	}
?>