<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBackendUser extends ProtoBaseEntity
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 255, true, true, false, null, null),
						'login' => LightMetaProperty::fill(new LightMetaProperty(), 'login', null, 'string', null, 255, true, true, false, null, null),
						'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 32, true, true, false, null, null),
						'lastName' => LightMetaProperty::fill(new LightMetaProperty(), 'lastName', 'last_name', 'string', null, 255, false, true, false, null, null),
						'firstName' => LightMetaProperty::fill(new LightMetaProperty(), 'firstName', 'first_name', 'string', null, 255, false, true, false, null, null),
						'midName' => LightMetaProperty::fill(new LightMetaProperty(), 'midName', 'mid_name', 'string', null, 255, false, true, false, null, null),
						'mobilePhone' => LightMetaProperty::fill(new LightMetaProperty(), 'mobilePhone', 'mobile_phone', 'string', null, 255, false, true, false, null, null),
						'workPhone' => LightMetaProperty::fill(new LightMetaProperty(), 'workPhone', 'work_phone', 'string', null, 255, false, true, false, null, null),
						'gender' => LightMetaProperty::fill(new LightMetaProperty(), 'gender', null, 'string', null, 1, false, true, false, null, null),
						'textShort' => LightMetaProperty::fill(new LightMetaProperty(), 'textShort', 'text_short', 'string', null, 65536, false, true, false, null, null),
						'text' => LightMetaProperty::fill(new LightMetaProperty(), 'text', null, 'string', null, 65536, false, true, false, null, null),
						'isSuperAdmin' => LightMetaProperty::fill(new LightMetaProperty(), 'isSuperAdmin', 'is_super_admin', 'boolean', null, null, false, true, false, null, null),
						'accessRoles' => LightMetaProperty::fill(new LightMetaProperty(), 'accessRoles', 'backend_user_role_id', 'identifierList', 'BackendUserRole', null, false, false, false, 3, null),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'BackendUser', 4, true, true, false, null, null)
					)
				);
		}
	}
?>