<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoBaseEntity extends ProtoBaseStorable
	{
		protected function makePropertyList()
		{
			return
				array_merge(
					parent::makePropertyList(),
					array(
						'createdAt' => LightMetaProperty::fill(new LightMetaProperty(), 'createdAt', 'created_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
						'updatedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'updatedAt', 'updated_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
						'deletedAt' => LightMetaProperty::fill(new LightMetaProperty(), 'deletedAt', 'deleted_at', 'timestampTZ', 'TimestampTZ', null, false, true, false, null, null),
						'displayOrder' => LightMetaProperty::fill(new LightMetaProperty(), 'displayOrder', 'display_order', 'integer', null, 4, false, true, false, null, null),
						'isActive' => LightMetaProperty::fill(new LightMetaProperty(), 'isActive', 'is_active', 'boolean', null, null, false, true, false, null, null),
						'isVisible' => LightMetaProperty::fill(new LightMetaProperty(), 'isVisible', 'is_visible', 'boolean', null, null, false, true, false, null, null),
						'isDeleted' => LightMetaProperty::fill(new LightMetaProperty(), 'isDeleted', 'is_deleted', 'boolean', null, null, false, true, false, null, null),
						'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'BaseEntity', 4, true, true, false, null, null)
					)
				);
		}
	}
?>