<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-22 19:02:51                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoBackendAccessResource extends BaseEntity
	{
		protected $parent = null;
		protected $type = null;
		protected $name = null;
		protected $title = null;
		
		/**
		 * @return BackendAccessResource
		**/
		public function getParent()
		{
			return $this->parent;
		}
		
		/**
		 * @return BackendAccessResource
		**/
		public function setParent(BackendAccessResource $parent = null)
		{
			$this->parent = $parent;
			
			return $this;
		}
		
		/**
		 * @return BackendAccessResource
		**/
		public function dropParent()
		{
			$this->parent = null;
			
			return $this;
		}
		
		/**
		 * @return EnumBackendAccessResourceType
		**/
		public function getType()
		{
			return $this->type;
		}
		
		/**
		 * @return BackendAccessResource
		**/
		public function setType(EnumBackendAccessResourceType $type)
		{
			$this->type = $type;
			
			return $this;
		}
		
		/**
		 * @return BackendAccessResource
		**/
		public function dropType()
		{
			$this->type = null;
			
			return $this;
		}
		
		public function getName()
		{
			return $this->name;
		}
		
		/**
		 * @return BackendAccessResource
		**/
		public function setName($name)
		{
			$this->name = $name;
			
			return $this;
		}
		
		public function getTitle()
		{
			return $this->title;
		}
		
		/**
		 * @return BackendAccessResource
		**/
		public function setTitle($title)
		{
			$this->title = $title;
			
			return $this;
		}
	}
?>