<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2014-07-23 08:21:16                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoEmployee extends BaseEntityWithTexts
	{
		protected $email = null;
		protected $firstName = null;
		protected $lastName = null;
		protected $middleName = null;
		protected $mobilePhone = null;
		protected $workPhone = null;
		protected $gender = 'u';
		protected $position = null;
		protected $birthDate = null;
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return Employee
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getFirstName()
		{
			return $this->firstName;
		}
		
		/**
		 * @return Employee
		**/
		public function setFirstName($firstName)
		{
			$this->firstName = $firstName;
			
			return $this;
		}
		
		public function getLastName()
		{
			return $this->lastName;
		}
		
		/**
		 * @return Employee
		**/
		public function setLastName($lastName)
		{
			$this->lastName = $lastName;
			
			return $this;
		}
		
		public function getMiddleName()
		{
			return $this->middleName;
		}
		
		/**
		 * @return Employee
		**/
		public function setMiddleName($middleName)
		{
			$this->middleName = $middleName;
			
			return $this;
		}
		
		public function getMobilePhone()
		{
			return $this->mobilePhone;
		}
		
		/**
		 * @return Employee
		**/
		public function setMobilePhone($mobilePhone)
		{
			$this->mobilePhone = $mobilePhone;
			
			return $this;
		}
		
		public function getWorkPhone()
		{
			return $this->workPhone;
		}
		
		/**
		 * @return Employee
		**/
		public function setWorkPhone($workPhone)
		{
			$this->workPhone = $workPhone;
			
			return $this;
		}
		
		public function getGender()
		{
			return $this->gender;
		}
		
		/**
		 * @return Employee
		**/
		public function setGender($gender)
		{
			$this->gender = $gender;
			
			return $this;
		}
		
		public function getPosition()
		{
			return $this->position;
		}
		
		/**
		 * @return Employee
		**/
		public function setPosition($position)
		{
			$this->position = $position;
			
			return $this;
		}
		
		/**
		 * @return Date
		**/
		public function getBirthDate()
		{
			return $this->birthDate;
		}
		
		/**
		 * @return Employee
		**/
		public function setBirthDate(Date $birthDate = null)
		{
			$this->birthDate = $birthDate;
			
			return $this;
		}
		
		/**
		 * @return Employee
		**/
		public function dropBirthDate()
		{
			$this->birthDate = null;
			
			return $this;
		}
	}
?>